# Generated by Django 4.1.4 on 2023-05-12 10:40

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(
                blank=True, max_length=60, null=True, verbose_name="نام کامل"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="identity",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="لازم است. ۱۵۰ حرف یا کمتر. فقط حروف, اعداد و @/./+/-/_",
                max_length=60,
                primary_key=True,
                serialize=False,
                unique=True,
                validators=[accounts.models.UsernameValidator()],
                verbose_name="شناسه",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="type",
            field=models.CharField(
                choices=[("H", "Headmaster"), ("S", "Staff"), ("T", "Teacher")],
                default="H",
                max_length=1,
                verbose_name="نوع کاربر",
            ),
        ),
    ]
