# Generated by Django 4.1.4 on 2023-05-13 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_user_options_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="type",
            field=models.CharField(
                choices=[("H", "مدیر"), ("S", "معاون"), ("T", "معلم")],
                max_length=1,
                verbose_name="نوع کاربر",
            ),
        ),
    ]
