# Generated by Django 4.1.4 on 2023-03-17 17:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "class_id",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lesson_name", models.CharField(max_length=50)),
                (
                    "teacher",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teached_lessons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WeeklySchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monday",
                    models.ManyToManyField(
                        related_name="monday", to="attendance.lesson"
                    ),
                ),
                (
                    "satureday",
                    models.ManyToManyField(
                        related_name="satureday", to="attendance.lesson"
                    ),
                ),
                (
                    "sunday",
                    models.ManyToManyField(
                        related_name="sunday", to="attendance.lesson"
                    ),
                ),
                (
                    "tuesday",
                    models.ManyToManyField(
                        related_name="tuesday", to="attendance.lesson"
                    ),
                ),
                (
                    "wednesday",
                    models.ManyToManyField(
                        related_name="wednesday", to="attendance.lesson"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=50, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=50, verbose_name="Last Name"),
                ),
                (
                    "number",
                    models.CharField(max_length=11, verbose_name="Phone Number"),
                ),
                (
                    "class_room",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="students",
                        to="attendance.class",
                        verbose_name="Class",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="class",
            name="weekly_schedule",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="class_room",
                to="attendance.weeklyschedule",
            ),
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=datetime.datetime.now)),
                (
                    "absents",
                    models.ManyToManyField(
                        blank=True, related_name="absent", to="attendance.student"
                    ),
                ),
                (
                    "class_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="attendance.class",
                    ),
                ),
                (
                    "presents",
                    models.ManyToManyField(
                        blank=True, related_name="present", to="attendance.student"
                    ),
                ),
            ],
            options={
                "unique_together": {("class_room", "date")},
            },
        ),
    ]
