# Generated by Django 4.1.4 on 2022-12-08 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="presents",
            field=models.ManyToManyField(
                related_name="present", to="attendance.student"
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="absents",
            field=models.ManyToManyField(
                related_name="absent", to="attendance.student"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="class_room",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="attendance.class",
                verbose_name="Class",
            ),
        ),
    ]
