# Generated by Django 4.1.4 on 2022-12-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_attendance_presents_alter_attendance_absents_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="absents",
            field=models.ManyToManyField(
                blank=True, related_name="absent", to="attendance.student"
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="presents",
            field=models.ManyToManyField(
                blank=True, related_name="present", to="attendance.student"
            ),
        ),
    ]
