# Generated by Django 4.1.4 on 2023-04-11 06:55

import attendance.models
import attendance.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_student_serial_code_student_student_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="image",
            field=models.ImageField(
                default="defaults/person.png",
                upload_to=attendance.models.student_image_upload,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="serial_code",
            field=models.CharField(
                max_length=6, validators=[attendance.validators.serial_code_validator]
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.CharField(
                max_length=10, validators=[attendance.validators.student_id_validator]
            ),
        ),
    ]
