# Generated by Django 4.1.4 on 2022-12-15 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_alter_attendance_absents_alter_attendance_presents"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("class_room", "date")},
        ),
    ]
