# Generated by Django 4.1.4 on 2023-03-15 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("attendance", "0004_alter_attendance_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lesson_name", models.CharField(max_length=50)),
                (
                    "teacher",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teached_lessons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("lesson_name", "teacher")},
            },
        ),
        migrations.CreateModel(
            name="WeeklySchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "class_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_schedule",
                        to="attendance.class",
                    ),
                ),
                (
                    "monday",
                    models.ManyToManyField(
                        related_name="monday", to="attendance.lesson"
                    ),
                ),
                (
                    "satureday",
                    models.ManyToManyField(
                        related_name="satureday", to="attendance.lesson"
                    ),
                ),
                (
                    "sunday",
                    models.ManyToManyField(
                        related_name="sunday", to="attendance.lesson"
                    ),
                ),
                (
                    "tuesday",
                    models.ManyToManyField(
                        related_name="tuesday", to="attendance.lesson"
                    ),
                ),
                (
                    "wednesday",
                    models.ManyToManyField(
                        related_name="wednesday", to="attendance.lesson"
                    ),
                ),
            ],
        ),
    ]
