# Generated by Django 4.1.4 on 2023-04-20 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0004_student_image_alter_student_serial_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="weekly_schedule",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="class_room",
                to="attendance.weeklyschedule",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="teacher",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
