# Generated by Django 4.1.4 on 2023-03-15 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_lesson_weeklyschedule"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weeklyschedule",
            name="class_room",
        ),
        migrations.AddField(
            model_name="class",
            name="weekly_schedule",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="attendance.weeklyschedule",
            ),
        ),
    ]
