# Generated by Django 4.1.4 on 2023-04-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_alter_class_weekly_schedule_alter_lesson_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="priority",
            field=models.IntegerField(default=1),
        ),
    ]
