# Generated by Django 4.1.4 on 2023-03-15 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0006_remove_weeklyschedule_class_room_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="weekly_schedule",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="class_room",
                to="attendance.weeklyschedule",
            ),
        ),
    ]
