# Generated by Django 4.1.4 on 2023-03-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0007_alter_class_weekly_schedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="class_id",
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
