# Generated by Django 4.1.4 on 2023-05-13 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0008_student_discipline"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="class",
            options={
                "ordering": ["-class_id"],
                "verbose_name": "کلاس",
                "verbose_name_plural": "کلاس ها",
            },
        ),
        migrations.AlterModelOptions(
            name="student",
            options={
                "verbose_name": "دانش آموز",
                "verbose_name_plural": "دانش آموز ها",
            },
        ),
    ]
