# Generated by Django 4.1.4 on 2023-06-17 12:40

import attendance.models
import attendance.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0009_alter_class_options_alter_student_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="class_room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="attendance.class",
                verbose_name="کلاس",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="discipline",
            field=models.CharField(
                choices=[
                    ("red", "red"),
                    ("green", "green"),
                    ("white", "white"),
                    ("yellow", "yellow"),
                ],
                default="white",
                max_length=6,
                verbose_name="سطح انظباط",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="first_name",
            field=models.CharField(max_length=50, verbose_name="نام"),
        ),
        migrations.AlterField(
            model_name="student",
            name="image",
            field=models.ImageField(
                blank=True,
                default="defaults/person.png",
                upload_to=attendance.models.student_image_upload,
                verbose_name="عکس",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="last_name",
            field=models.CharField(max_length=50, verbose_name="نام خانوادگی"),
        ),
        migrations.AlterField(
            model_name="student",
            name="number",
            field=models.CharField(max_length=11, verbose_name="شماره تلفن"),
        ),
        migrations.AlterField(
            model_name="student",
            name="serial_code",
            field=models.CharField(
                max_length=6,
                validators=[attendance.validators.serial_code_validator],
                verbose_name="کد سریال شناسنامه",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.CharField(
                max_length=10,
                validators=[attendance.validators.student_id_validator],
                verbose_name="شماره شناسنامه",
            ),
        ),
    ]
